calendar/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MyCalendar.as_view(), name='calendar'),
    path('<int:year>/<int:month>/<int:day>/',
        views.MyCalendar.as_view(), name='calendar'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schedule.urls')),
]

schedule/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MyCalendar.as_view(), name='schedule'),
    path('<int:year>/<int:month>/<int:day>/',
        views.MyCalendar.as_view(), name='schedule'),
]

schedule/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

schedule/forms.py
from django import forms
from .models import Schedule


class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time

app/views.py
import datetime
from django.shortcuts import redirect, render
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule

class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'app/includes/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'app/includes/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return render(self.template_name,context)

from .models import Schedule

class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'app/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)

calendar/views.py
import datetime
from django.shortcuts import redirect, render
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule

class Monthcalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'calendar/includes/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class Weekcalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'calendar/includes/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return render(self.template_name,context)

from .models import Schedule

class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'calendar/index.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('calendar', year=date.year, month=date.month, day=date.day)

schedule/views.py
import datetime
from django.shortcuts import redirect, render
from django.views import generic
from . import mixins
from .forms import BS4ScheduleForm
from .models import Schedule

class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'schedule/includes/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'schedule/includes/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return render(self.template_name,context)

from .models import Schedule

class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'schedule/index.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('schedule', year=date.year, month=date.month, day=date.day)

templates/app/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="/">一覧</a>
                <a class="navbar-brand" href="/">詳細</a>
        </nav>
<div class="container" mt-3>
    {% block content %}
        <p>※コンテンツがありません。</p>
    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

templates/app/includes/month.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
                {% if w == '土' %}
                    <td class="table-primary">
                {% elif w == '日' %}
                    <td class="table-success">
                {% else %}
                <th>
                {% endif %}      
                 {{ w }}</th>
            {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                    <td>
                <a href="{% url 'app:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/app/includes/week.html
{% extends 'app/base.html' %}
{% block content %}
<a href="{% url 'app:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'app:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
                <td>
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>
{% endblock %}

templates/app/mycalendar.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'app/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <input type="submit" value="送信" class="btn btn-primary btn-block"/>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'app/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/calendar/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>
        {% block navbar %}
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="{% url 'calendar' %}">カレンダー</a>
                </nav>
        {% endblock %}
<div class="container" mt-3>
    {% block content %}
        <p>※コンテンツがありません。</p>
    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

templates/calendar/includes/month.html
{% extends 'calendar/base.html' %}
{% block navbar %}{% endblock %}
{% block content %}
    <a href="{% url 'calendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'calendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
                {% if w == '土' %}
                    <td class="table-primary">
                {% elif w == '日' %}
                    <td class="table-success">
                {% else %}
                <th>
                {% endif %}      
                 {{ w }}</th>
            {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                    <td>
                <a href="{% url 'calendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/calendar/includes/week.html
{% extends 'calendar/base.html' %}
{% block navbar %}{% endblock %}
{% block content %}
<a href="{% url 'calendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'calendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
                <td>
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>
{% endblock %}

templates/calendar/index.html
{% extends 'calendar/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'calendar/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <input type="submit" value="送信" class="btn btn-primary btn-block"/>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'calendar/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/schedule/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>
        {% block navbar %}
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="{% url 'schedule' %}">カレンダー</a>
                </nav>
        {% endblock %}
<div class="container" mt-3>
    {% block content %}
        <p>※コンテンツがありません。</p>
    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

templates/schedule/includes/month.html
{% extends 'schedule/base.html' %}
{% block navbar %}{% endblock %}
{% block content %}
    <a href="{% url 'schedule' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'schedule' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
                {% if w == '土' %}
                    <td class="table-primary">
                {% elif w == '日' %}
                    <td class="table-success">
                {% else %}
                <th>
                {% endif %}      
                 {{ w }}</th>
            {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                    <td>
                <a href="{% url 'schedule' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/schedule/includes/week.html
{% extends 'schedule/base.html' %}
{% block navbar %}{% endblock %}
{% block content %}
<a href="{% url 'schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'schedule' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
                <td>
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>
{% endblock %}

templates/schedule/index.html
{% extends 'schedule/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'schedule/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <input type="submit" value="送信" class="btn btn-primary btn-block"/>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'schedule/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}